version: '3'
services:
  api:
    build: ./api/
    container_name: api
    env_file:
      - ./api/.env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - network
  context_aware:
    build: ./context_aware/
    container_name: context_aware
    volumes:
      - ./context_aware/contextaware/classifier/working_dataset.csv:/context_aware/contextaware/classifier/working_dataset.csv
      - ./context_aware/contextaware/classifier/working_model.sav:/context_aware/contextaware/classifier/working_model.sav
    ports:
      - 4000:4000
    networks:
      - network

networks:
  network:
    driver: bridge
